// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvEMXlsmRqPEDqcYKvcIC8M-IEH9xCCiM',
    appId: '1:107638449100:web:9a0c9c0f0223385ad7f369',
    messagingSenderId: '107638449100',
    projectId: 'auth-store-e077c',
    authDomain: 'auth-store-e077c.firebaseapp.com',
    storageBucket: 'auth-store-e077c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvF9tigLxYWAJ-FriXD4pnkqNQsCpqadA',
    appId: '1:107638449100:android:f842d0b33e89737ad7f369',
    messagingSenderId: '107638449100',
    projectId: 'auth-store-e077c',
    storageBucket: 'auth-store-e077c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZeYnyg18pJhNLfyUvMmBpXtmt0OUSNmY',
    appId: '1:107638449100:ios:8014aef08500302cd7f369',
    messagingSenderId: '107638449100',
    projectId: 'auth-store-e077c',
    storageBucket: 'auth-store-e077c.appspot.com',
    iosClientId: '107638449100-tjh8e4striblvcpusm802ba3e36df97e.apps.googleusercontent.com',
    iosBundleId: 'com.example.authandstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZeYnyg18pJhNLfyUvMmBpXtmt0OUSNmY',
    appId: '1:107638449100:ios:8014aef08500302cd7f369',
    messagingSenderId: '107638449100',
    projectId: 'auth-store-e077c',
    storageBucket: 'auth-store-e077c.appspot.com',
    iosClientId: '107638449100-tjh8e4striblvcpusm802ba3e36df97e.apps.googleusercontent.com',
    iosBundleId: 'com.example.authandstore',
  );
}
